app:
  image: 063884341009.dkr.ecr.us-east-1.amazonaws.com/vprofileappimg
  tag: beb53674442a0e27e240449eb9b6b3658641aed0
  replicas: 1
  containerPort: 8080
  servicePort: 8080
  defaultUser: ""
db:
  image: vprocontainers/vprofiledb
  tag: latest
  replicas: 1
  containerPort: 3306
  servicePort: 3306
  storageClass: gp2
  storageSize: 3Gi
  defaultUser: root
memcached:
  image: memcached
  tag: latest
  replicas: 1
  containerPort: 11211
  servicePort: 11211
rabbitmq:
  image: rabbitmq
  tag: latest
  replicas: 1
  containerPort: 5672
  servicePort: 5672
  defaultUser: guest
initcontainers:
  app:
    image: busybox
    tag: latest
  db:
    image: busybox
    tag: latest
ingress:
  enabled: true
  host: vprofile.salmancloud.xyz
  servicePort: 8080
secrets:
  dbPass: vprodbpass
  rmqPass: guest
dockerregistry:
  enabled: false
  server: ""
  username: ""
  password: ""
  email: ""
