apiVersion: apps/v1
kind: Deployment
metadata:
  name: vprodb
  labels:
    app: vprodb
spec:
  replicas: {{ .Values.db.replicas }}
  selector:
    matchLabels:
      app: vprodb
  template:
    metadata:
      labels:
        app: vprodb
    spec:
      {{- if .Values.dockerregistry.enabled }}
      imagePullSecrets:
        - name: {{ .Release.Name }}-docker-registry
      {{- end }}
      containers:
        - name: vprodb
          image: {{ .Values.db.image }}:{{ .Values.db.tag }}
          imagePullPolicy: Always
          ports:
            - name: vprodb-port
              containerPort: {{ .Values.db.containerPort }}
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: db-pass
          volumeMounts:
            - name: vpro-db-data
              mountPath: /var/lib/mysql
      initContainers:
        - name: busybox
          image: {{ .Values.initcontainers.db.image }}:{{ .Values.initcontainers.db.tag }}
          command:
            - sh
            - -c
            - rm -rf /var/lib/mysql/lost+found
          volumeMounts:
            - name: vpro-db-data
              mountPath: /var/lib/mysql
      volumes:
        - name: vpro-db-data
          persistentVolumeClaim:
            claimName: db-pv-claim
