{{- if .Values.dockerregistry.enabled }}
{{- $auth := printf "%s:%s" .Values.dockerregistry.username .Values.dockerregistry.password | b64enc -}}
{{- $dockerConfig := dict "auths" (dict .Values.dockerregistry.server (dict "username" .Values.dockerregistry.username "password" .Values.dockerregistry.password "email" .Values.dockerregistry.email "auth" $auth)) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-docker-registry
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ $dockerConfig | toJson | b64enc | quote }}
{{- end }}
