apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pv-claim
  labels:
    app: vprodb
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.db.storageClass | quote }}
  resources:
    requests:
      storage: {{ .Values.db.storageSize }}
