apiVersion: v1
kind: Service
metadata:
  name: vproapp-service
spec:
  type: ClusterIP
  selector:
    app: vproapp
  ports:
    - port: {{ .Values.app.servicePort }}
      targetPort: {{ .Values.app.containerPort }}
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: vprodb
spec:
  type: ClusterIP
  selector:
    app: vprodb
  ports:
    - port: {{ .Values.db.servicePort }}
      targetPort: {{ .Values.db.containerPort }}
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: vprocache01
spec:
  type: ClusterIP
  selector:
    app: vpromc
  ports:
    - port: {{ .Values.memcached.servicePort }}
      targetPort: {{ .Values.memcached.containerPort }}
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: vpromq01
spec:
  type: ClusterIP
  selector:
    app: vpromq01
  ports:
    - port: {{ .Values.rabbitmq.servicePort }}
      targetPort: {{ .Values.rabbitmq.containerPort }}
      protocol: TCP
